### ISSUE TITLE
Stopped app when searching any word.

### ISSUE THREAD

**Issue by Chirag27592** [iammert/InstagramTags#1]
Caused by: rx.exceptions.OnErrorNotImplementedException: HTTP 400 Bad Request

```
FATAL EXCEPTION: main
                                                                           Process: iammert.com.instagramtags, PID: 16947
                                                                           java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
                                                                               at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
                                                                               at android.os.Handler.handleCallback(Handler.java:746)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                            Caused by: rx.exceptions.OnErrorNotImplementedException: HTTP 400 Bad Request
                                                                               at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:374)
                                                                               at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:371)
                                                                               at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                                                                               at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
                                                                               at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                               at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
                                                                               at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
                                                                               at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
                                                                               at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:810)
                                                                               at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:571)
                                                                               at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:560)
                                                                               at rx.internal.operators.OperatorMerge$InnerSubscriber.onError(OperatorMerge.java:844)
                                                                               at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:264)
                                                                               at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:207)
                                                                               at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                               at android.os.Handler.handleCallback(Handler.java:746) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                               at android.os.Looper.loop(Looper.java:148) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                            Caused by: retrofit2.adapter.rxjava.HttpException: HTTP 400 Bad Request
                                                                               at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:43)
                                                                               at retrofit2.adapter.rxjava.OperatorMapResponseToBodyOrError$1.onNext(OperatorMapResponseToBodyOrError.java:38)
                                                                               at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
                                                                               at rx.Subscriber.setProducer(Subscriber.java:211)
                                                                               at rx.Subscriber.setProducer(Subscriber.java:205)
                                                                               at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
                                                                               at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
                                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                               at rx.Observable.unsafeSubscribe(Observable.java:8460)
                                                                               at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
                                                                               at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
                                                                               at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
                                                                               at iammert.com.instagramtags.model.preferences.PreferencesHelperImpl.lambda$get$1(PreferencesHelperImpl.java:40)
                                                                               at iammert.com.instagramtags.model.preferences.PreferencesHelperImpl.access$lambda$1(PreferencesHelperImpl.java:0)
                                                                               at iammert.com.instagramtags.model.preferences.PreferencesHelperImpl$$Lambda$2.call(Unknown Source)
                                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                               at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                               at rx.Observable.unsafeSubscribe(Observable.java:8460)
                                                                               at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                           	at rx.internal.schedulers.CachedThreadScheduler$EventLoop
```

**Comment by iammert** [comment]
Ok, my bad. I forgot to handle onError on that observable. But you should create a instagram client on Developer Console and give that client ID to Constants class. Did you already? @Chirag27592

**Comment by iammert** [comment]
c3c6353376a50cb85999d0f5461e197729d6ad03 fixed by showing info dialog.
